spring:

  application:
    name: TinyFlow
  datasource:
    url: jdbc:mysql://localhost:3306/tiny-flow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 20
      connection-timeout: 3000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 47.97.110.128
      port: 6379
      password: 123456
      timeout: 2s
      lettuce:
          pool:
            max-active: 600
            max-idle: 200
            max-wait: 1s
            min-idle: 50


server:
  port: 8080
  tomcat:
    threads:
      max: 600
      min-spare: 50
    accept-count: 2000
    max-connections: 30000
    connection-timeout: 3000
  servlet:
    encoding:
      charset: UTF-8
      force: true


app:
  domain: http://localhost:8080

shortcode:
  minLen: 4
  mask: 0x9E3779B97F4A7C15


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: tinyflow
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.95, 0.99

events:
  sampleRate: 0.0
clicks:
  mode: local

cache:
  caffeine:
    spec: maximumSize=50000,expireAfterWrite=30m,recordStats
  warmup:
    enabled: true
    size: 5000

resilience4j:
  ratelimiter:
    instances:
      redirectLimit:
        limitForPeriod: 3500
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      redisBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
