spring:

  application:
    name: TinyFlow
  datasource:
    url: jdbc:mysql://localhost:3306/tiny-flow?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: 47.97.110.128
      port: 6379
      password: 123456
      timeout: 2s
      lettuce:
          pool:
            max-active: 400

            max-idle: 100

            max-wait: 2s
            min-idle: 20


server:
  port: 8080
  tomcat:
    threads:
      max: 400
    accept-count: 1000
    max-connections: 20000
  servlet:
    encoding:
      charset: UTF-8
      force: true


app:
  domain: http://localhost:8080

shortcode:
  minLen: 4
  mask: 0x9E3779B97F4A7C15


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: tinyflow
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
      percentiles:
        http:
          server:
            requests: 0.95, 0.99

events:
  sampleRate: 0.0
clicks:
  mode: local

resilience4j:
  ratelimiter:
    instances:
      redirectLimit:
        limitForPeriod: 4500
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  circuitbreaker:
    instances:
      redisBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
